import Product from "../models/Product";
const mockData = [
  new Product(
    "SS002",
    "Trenton modular sofa_3",
    "Setting the bar as one of the loudest speakers in its class, the Kilburn is a compact, stout-hearted hero with a well-balanced audio which boasts a clear midrange and extended highs for a sound.",
    25000,
    "Sofas",
    ["Sofa", "Chair", "Home", "Shop"],
    ["#816DFA", "#000000", "#CDBA7B"],
    ["L", "XL", "XS"],
    null,
    [],
    require("../../assets/svgs/ss002_1.png"),
    [require("../../assets/svgs/ss002_1.png")]
  ),
  new Product(
    "SS003",
    "Trenton modular sofa_3",
    "Setting the bar as one of the loudest speakers in its class, the Kilburn is a compact, stout-hearted hero with a well-balanced audio which boasts a clear midrange and extended highs for a sound.",
    280000,
    "Sofas",
    ["Sofa", "Chair", "Home", "Shop"],
    ["#816DFA", "#000000", "#CDBA7B"],
    ["L", "XL", "XS"],
    null,
    [],
    require("../../assets/svgs/ss003_1.png"),
    [require("../../assets/svgs/ss003_1.png")]
  ),
  new Product(
    "SS004",
    "Trenton modular sofa_3",
    "Setting the bar as one of the loudest speakers in its class, the Kilburn is a compact, stout-hearted hero with a well-balanced audio which boasts a clear midrange and extended highs for a sound.",
    450000,
    "Sofas",
    ["Sofa", "Chair", "Home", "Shop"],
    ["#816DFA", "#000000", "#CDBA7B"],
    ["L", "XL", "XS"],
    null,
    [],
    require("../../assets/svgs/ss004_1.png"),
    [require("../../assets/svgs/ss004_1.png")]
  ),
  new Product(
    "SS005",
    "Trenton modular sofa_3",
    "Setting the bar as one of the loudest speakers in its class, the Kilburn is a compact, stout-hearted hero with a well-balanced audio which boasts a clear midrange and extended highs for a sound.",
    35000,
    "Sofas",
    ["Sofa", "Chair", "Home", "Shop"],
    ["#816DFA", "#000000", "#CDBA7B"],
    ["L", "XL", "XS"],
    null,
    [],
    require("../../assets/svgs/ss005_1.png"),
    [require("../../assets/svgs/ss005_1.png")]
  ),
  new Product(
    "SS006",
    "Trenton modular sofa_3",
    "Setting the bar as one of the loudest speakers in its class, the Kilburn is a compact, stout-hearted hero with a well-balanced audio which boasts a clear midrange and extended highs for a sound.",
    15000,
    "Sofas",
    ["Sofa", "Chair", "Home", "Shop"],
    ["#816DFA", "#000000", "#CDBA7B"],
    ["L", "XL", "XS"],
    null,
    [],
    require("../../assets/svgs/ss006_1.png"),
    [require("../../assets/svgs/ss006_1.png")]
  ),
  new Product(
    "SS007",
    "Trenton modular sofa_3",
    "Setting the bar as one of the loudest speakers in its class, the Kilburn is a compact, stout-hearted hero with a well-balanced audio which boasts a clear midrange and extended highs for a sound.",
    20000,
    "Sofas",
    ["Sofa", "Chair", "Home", "Shop"],
    ["#816DFA", "#000000", "#CDBA7B"],
    ["L", "XL", "XS"],
    null,
    [],
    require("../../assets/svgs/ss007_1.png"),
    [require("../../assets/svgs/ss007_1.png")]
  ),
  new Product(
    "SS008",
    "Trenton modular sofa_3",
    "Setting the bar as one of the loudest speakers in its class, the Kilburn is a compact, stout-hearted hero with a well-balanced audio which boasts a clear midrange and extended highs for a sound.",
    18000,
    "Sofas",
    ["Sofa", "Chair", "Home", "Shop"],
    ["#816DFA", "#000000", "#CDBA7B"],
    ["L", "XL", "XS"],
    null,
    [],
    require("../../assets/svgs/ss008_1.png"),
    [require("../../assets/svgs/ss008_1.png")]
  ),
  new Product(
    "SS009",
    "Trenton modular sofa_3",
    "Setting the bar as one of the loudest speakers in its class, the Kilburn is a compact, stout-hearted hero with a well-balanced audio which boasts a clear midrange and extended highs for a sound.",
    45000,
    "Sofas",
    ["Sofa", "Chair", "Home", "Shop"],
    ["#816DFA", "#000000", "#CDBA7B"],
    ["L", "XL", "XS"],
    null,
    [],
    require("../../assets/svgs/ss009_1.png"),
    [require("../../assets/svgs/ss009_1.png")]
  ),
  new Product(
    "SS010",
    "Trenton modular sofa_3",
    "Setting the bar as one of the loudest speakers in its class, the Kilburn is a compact, stout-hearted hero with a well-balanced audio which boasts a clear midrange and extended highs for a sound.",
    25000,
    "Sofas",
    ["Sofa", "Chair", "Home", "Shop"],
    ["#816DFA", "#000000", "#CDBA7B"],
    ["L", "XL", "XS"],
    null,
    [],
    require("../../assets/svgs/ss010_1.png"),
    [require("../../assets/svgs/ss010_1.png")]
  ),
  new Product(
    "SS011",
    "Trenton modular sofa_3",
    "Setting the bar as one of the loudest speakers in its class, the Kilburn is a compact, stout-hearted hero with a well-balanced audio which boasts a clear midrange and extended highs for a sound.",
    250000,
    "Sofas",
    ["Sofa", "Chair", "Home", "Shop"],
    ["#816DFA", "#000000", "#CDBA7B"],
    ["L", "XL", "XS"],
    null,
    [],
    require("../../assets/svgs/ss011_1.png"),
    [require("../../assets/svgs/ss011_1.png")]
  ),
  new Product(
    "SS012",
    "Trenton modular sofa_3",
    "Setting the bar as one of the loudest speakers in its class, the Kilburn is a compact, stout-hearted hero with a well-balanced audio which boasts a clear midrange and extended highs for a sound.",
    48000,
    "Sofas",
    ["Sofa", "Chair", "Home", "Shop"],
    ["#816DFA", "#000000", "#CDBA7B"],
    ["L", "XL", "XS"],
    null,
    [],
    require("../../assets/svgs/ss012_1.png"),
    [require("../../assets/svgs/ss012_1.png")]
  ),
  new Product(
    "SS013",
    "Trenton modular sofa_3",
    "Setting the bar as one of the loudest speakers in its class, the Kilburn is a compact, stout-hearted hero with a well-balanced audio which boasts a clear midrange and extended highs for a sound.",
    55000,
    "Sofas",
    ["Sofa", "Chair", "Home", "Shop"],
    ["#816DFA", "#000000", "#CDBA7B"],
    ["L", "XL", "XS"],
    null,
    [],
    require("../../assets/svgs/ss013_1.png"),
    [require("../../assets/svgs/ss013_1.png")]
  ),
  new Product(
    "SS014",
    "Trenton modular sofa_3",
    "Setting the bar as one of the loudest speakers in its class, the Kilburn is a compact, stout-hearted hero with a well-balanced audio which boasts a clear midrange and extended highs for a sound.",
    35000,
    "Sofas",
    ["Sofa", "Chair", "Home", "Shop"],
    ["#816DFA", "#000000", "#CDBA7B"],
    ["L", "XL", "XS"],
    null,
    [],
    require("../../assets/svgs/ss014_1.png"),
    [require("../../assets/svgs/ss014_1.png")]
  ),
  new Product(
    "SS001",
    "Asgaard Sofa",
    "Setting the bar as one of the loudest speakers in its class, the Kilburn is a compact, stout-hearted hero with a well-balanced audio which boasts a clear midrange and extended highs for a sound.",
    250000,
    "Sofas",
    ["Sofa", "Chair", "Home", "Shop"],
    ["#816DFA", "#000000", "#CDBA7B"],
    ["L", "XL", "XS"],
    4.2,
    [],
    require("../../assets/svgs/ss001_1.png"),
    [
      require("../../assets/svgs/ss001_1.png"),
      require("../../assets/svgs/ss001_2.png"),
      require("../../assets/svgs/ss001_3.png"),
      require("../../assets/svgs/ss001_4.png"),
      require("../../assets/svgs/ss001_5.png")
    ]
  ),
  new Product(
    "SS015",
    "Trenton modular sofa_3",
    "Setting the bar as one of the loudest speakers in its class, the Kilburn is a compact, stout-hearted hero with a well-balanced audio which boasts a clear midrange and extended highs for a sound.",
    100000,
    "Sofas",
    ["Sofa", "Chair", "Home", "Shop"],
    ["#816DFA", "#000000", "#CDBA7B"],
    ["L", "XL", "XS"],
    null,
    [],
    require("../../assets/svgs/ss015_1.png"),
    [require("../../assets/svgs/ss015_1.png")]
  ),
  new Product(
    "SS016",
    "Trenton modular sofa_3",
    "Setting the bar as one of the loudest speakers in its class, the Kilburn is a compact, stout-hearted hero with a well-balanced audio which boasts a clear midrange and extended highs for a sound.",
    85000,
    "Sofas",
    ["Sofa", "Chair", "Home", "Shop"],
    ["#816DFA", "#000000", "#CDBA7B"],
    ["L", "XL", "XS"],
    null,
    [],
    require("../../assets/svgs/ss016_1.png"),
    [require("../../assets/svgs/ss016_1.png")]
  ),
  new Product(
    "SS017",
    "Trenton modular sofa_3",
    "Setting the bar as one of the loudest speakers in its class, the Kilburn is a compact, stout-hearted hero with a well-balanced audio which boasts a clear midrange and extended highs for a sound.",
    88000,
    "Sofas",
    ["Sofa", "Chair", "Home", "Shop"],
    ["#816DFA", "#000000", "#CDBA7B"],
    ["L", "XL", "XS"],
    null,
    [],
    require("../../assets/svgs/ss017_1.png"),
    [require("../../assets/svgs/ss017_1.png")]
  )
];

export default mockData;
